package frc.components;

public enum ArmHeight {
    HATCH_LOW, HATCH_MEDIUM, HATCH_HIGH, BALL_LOW, BALL_MEDIUM, BALL_HIGH, GROUND_PICKUP, POSITION_MANUAL, NO_CHANGE, NO_MOVEMENT, STOW, FULL_MANUAL;
}